@echo off
title GHOST AGENT v7.0 - INSTALLER
color 0A

echo.
echo ===================================================
echo   GHOST AGENT v7.1 - MODULAR INSTALLER
echo ===================================================
echo.

:: 1. Crear Directorio Principal
if not exist "C:\AntiGravityExt" (
    echo [+] Creando C:\AntiGravityExt...
    mkdir "C:\AntiGravityExt"
) else (
    echo [i] C:\AntiGravityExt ya existe.
)

:: 2. Instalar Extension
echo.
echo [1/3] Instalando Extension Modular...
set "EXT_DIR=%USERPROFILE%\AppData\Local\Programs\AntiGravity\resources\app\extensions\antigravity-internal-hook"

if not exist "%EXT_DIR%" mkdir "%EXT_DIR%" 2>NUL
if not exist "%EXT_DIR%\src" mkdir "%EXT_DIR%\src" 2>NUL

copy /Y "extension\extension.js" "%EXT_DIR%\" >NUL
copy /Y "extension\package.json" "%EXT_DIR%\" >NUL
copy /Y "extension\ghost_config.json" "C:\AntiGravityExt\" >NUL
xcopy "extension\src" "%EXT_DIR%\src" /E /I /Y >NUL

if exist "%EXT_DIR%\extension.js" (
    echo    [OK] Extension copiada exitosamente.
) else (
    echo    [X] ERROR al copiar extension.
)

:: 3. Crear BrowserAllowlist (CRITICO para v7.0)
echo.
echo [2/3] Generando MEGA BrowserAllowlist...
set "ALLOW_DIR=%USERPROFILE%\.gemini\antigravity"
set "ALLOW_FILE=%ALLOW_DIR%\browserAllowlist.txt"

if not exist "%ALLOW_DIR%" mkdir "%ALLOW_DIR%" 2>NUL

(
echo # MEGA BrowserAllowlist - Auto-generated by Ghost Agent v7.0
echo # Allows ALL traffic for unrestricted automation
echo *
echo *.*
echo *://*
echo http://*
echo https://*
echo localhost
echo localhost:*
echo *.localhost
echo 127.0.0.1:*
echo 192.168.*.*
echo *.com
echo *.net
echo *.org
echo *.io
echo *.dev
echo *.app
echo *.ai
echo *.cloud
echo *.github.io
echo *.vercel.app
echo *.netlify.app
) > "%ALLOW_FILE%"

if exist "%ALLOW_FILE%" (
    echo    [OK] Allowlist generada en: %ALLOW_FILE%
) else (
    echo    [X] ERROR generando allowlist.
)

:: 4. Finalizar
echo.
echo [3/3] Finalizando configuracion...
echo    [i] Configuracion JSON instalada en raiz.

echo.
echo ===================================================
echo   INSTALACION MODULAR COMPLETADA
echo ===================================================
echo.
echo [!] PASOS SIGUIENTES:
echo   1. Reinicia Antigravity IDE.
echo   2. Verifica que el archivo C:\AntiGravityExt\ghost_config.json existe.
echo.
pause
