@echo off
title GHOST AGENT v7.0 - INSTALLER
color 0A

echo.
echo ===================================================
echo   GHOST AGENT v7.0 - PRODUCTION INSTALLER
echo ===================================================
echo.

:: 1. Crear Directorio Principal
if not exist "C:\AntiGravityExt" (
    echo [+] Creando C:\AntiGravityExt...
    mkdir "C:\AntiGravityExt"
) else (
    echo [i] C:\AntiGravityExt ya existe.
)

:: 2. Instalar Extension
echo.
echo [1/3] Instalando Extension...
set "EXT_DIR=%USERPROFILE%\AppData\Local\Programs\AntiGravity\resources\app\extensions\antigravity-internal-hook"

if not exist "%EXT_DIR%" mkdir "%EXT_DIR%" 2>NUL

copy /Y "extension\extension.js" "%EXT_DIR%\" >NUL
copy /Y "extension\package.json" "%EXT_DIR%\" >NUL

if exist "%EXT_DIR%\extension.js" (
    echo    [OK] Extension copiada exitosamente.
) else (
    echo    [X] ERROR al copiar extension.
)

:: 3. Crear BrowserAllowlist (CRITICO para v7.0)
echo.
echo [2/3] Generando MEGA BrowserAllowlist...
set "ALLOW_DIR=%USERPROFILE%\.gemini\antigravity"
set "ALLOW_FILE=%ALLOW_DIR%\browserAllowlist.txt"

if not exist "%ALLOW_DIR%" mkdir "%ALLOW_DIR%" 2>NUL

(
echo # MEGA BrowserAllowlist - Auto-generated by Ghost Agent v7.0
echo # Allows ALL traffic for unrestricted automation
echo *
echo *.*
echo *://*
echo http://*
echo https://*
echo localhost
echo localhost:*
echo *.localhost
echo 127.0.0.1:*
echo 192.168.*.*
echo *.com
echo *.net
echo *.org
echo *.io
echo *.dev
echo *.app
echo *.ai
echo *.cloud
echo *.github.io
echo *.vercel.app
echo *.netlify.app
) > "%ALLOW_FILE%"

if exist "%ALLOW_FILE%" (
    echo    [OK] Allowlist generada en: %ALLOW_FILE%
) else (
    echo    [X] ERROR generando allowlist.
)

:: 4. Copiar Herramientas a C:\AntiGravityExt (si ejecutamos desde otro lado)
echo.
echo [3/3] Finalizando configuracion...
if /I not "%CD%"=="C:\AntiGravityExt" (
    copy /Y "GHOST_CONTROL_PANEL.ps1" "C:\AntiGravityExt\" >NUL
    copy /Y "START_GUI.bat" "C:\AntiGravityExt\" >NUL
    copy /Y "FIX_FOLDERS.bat" "C:\AntiGravityExt\" >NUL
    copy /Y "DIAGNOSTIC.bat" "C:\AntiGravityExt\" >NUL
    copy /Y "README.md" "C:\AntiGravityExt\" >NUL
    copy /Y "TROUBLESHOOTING.txt" "C:\AntiGravityExt\" >NUL
)

echo.
echo ===================================================
echo   INSTALACION COMPLETADA
echo ===================================================
echo.
echo [!] PASOS SIGUIENTES:
echo   1. Reinicia Antigravity IDE.
echo   2. Verifica que la barra inferior sea MORADA.
echo   3. Ejecuta START_GUI.bat para controlar el agente.
echo.
pause
