/**
 * Test First Autonomous Cycle
 * Tests the complete workflow: APIManager → Best API → Prompt Generation → GHOST_INPUT
 */

const APIManager = require('./src/apiManager');
const fs = require('fs');
const path = require('path');

async function testFirstCycle() {
    console.log('🧪 Testing First Autonomous Cycle\n');
    console.log('='.repeat(60) + '\n');

    // Initialize API Manager
    console.log('1️⃣  Initializing API Manager...');
    const apiManager = new APIManager();

    // Create test context (simulated)
    const testContext = {
        lastMessage: {
            content: `I have successfully completed the integration of the API testing system. 
            
All tests are now passing. The system includes:
- API key testing for all providers
- Rate limit monitoring
- Gray list for failed models
- Credit checking functionality

What should I do next?`
        },
        repoAnalysis: {
            filesChanged: [
                'apiKeyTester.js',
                'apiManager.js',
                'creditChecker.js',
                'grayListManager.js'
            ],
            diff: '',
            stats: {},
            errors: []
        },
        testResults: {
            status: 'passing',
            passed: 47,
            failed: 3,
            total: 50,
            passRate: 0.94
        },
        projectContext: {
            roadmap: 'Phase 7: Dual-Core Supervisor',
            conversationState: null
        },
        conversationState: {
            tasks_completed: 25,
            tasks_pending: 8,
            current_task: 'Testing Supervisor Extension',
            autonomous_cycles: 1
        }
    };

    console.log('✅ Context prepared');
    console.log(`   Tasks: ${testContext.conversationState.tasks_completed} done, ${testContext.conversationState.tasks_pending} pending`);
    console.log(`   Test Pass Rate: ${(testContext.testResults.passRate * 100).toFixed(1)}%`);
    console.log('');

    // Call API with intelligent fallback
    console.log('2️⃣  Calling AI Supervisor with intelligent fallback...\n');

    try {
        const result = await apiManager.callWithFallback(testContext);

        console.log('\n✅ API call successful!\n');
        console.log('Provider:', result.provider);
        console.log('Model:', result.model);
        console.log('Response Time:', result.responseTime, 'ms');
        console.log('Timestamp:', result.timestamp);
        console.log('');

        // Write to GHOST_INPUT.txt
        console.log('3️⃣  Writing prompt to GHOST_INPUT.txt...\n');

        const workspaceRoot = path.join(__dirname, '..');
        const ghostInputPath = path.join(workspaceRoot, 'GHOST_INPUT.txt');

        const promptWithMetadata = `[AUTO-GENERATED BY SUPERVISOR]
[Cycle: ${testContext.conversationState.autonomous_cycles}]
[Provider: ${result.provider} - ${result.model}]
[Timestamp: ${result.timestamp}]

${result.content}

---
[Next action will be auto-pasted by Internal Hook]`;

        fs.writeFileSync(ghostInputPath, promptWithMetadata, 'utf-8');

        console.log('✅ Prompt written successfully');
        console.log('   File:', ghostInputPath);
        console.log('   Length:', result.content.length, 'chars');
        console.log('');

        // Show prompt preview
        console.log('4️⃣  Generated Prompt Preview:\n');
        console.log('─'.repeat(60));
        console.log(result.content.substring(0, 500) + '...');
        console.log('─'.repeat(60));
        console.log('');

        // Session summary
        console.log('5️⃣  Session Summary:\n');
        const summary = apiManager.getSessionSummary();
        console.log('   Total Requests:', summary.requests);
        console.log('   Successes:', summary.successes);
        console.log('   Failures:', summary.failures);
        console.log('   Success Rate:', (summary.successRate * 100).toFixed(1) + '%');
        console.log('   Total Tokens:', summary.totalTokens);
        console.log('');

        console.log('='.repeat(60));
        console.log('🎉 FIRST AUTONOMOUS CYCLE COMPLETE!');
        console.log('='.repeat(60));
        console.log('');
        console.log('✅ All systems operational');
        console.log('✅ Intelligent API selection working');
        console.log('✅ Prompt generation successful');
        console.log('✅ GHOST_INPUT.txt ready for Internal Hook');
        console.log('');
        console.log('🚀 Ready for full autonomous operation!');

        return true;

    } catch (error) {
        console.error('\n❌ First cycle failed:', error.message);
        console.error('');
        console.error('Troubleshooting:');
        console.error('  1. Run: node apiKeyTester.js');
        console.error('  2. Verify working models in apiStats.json');
        console.error('  3. Check API keys are valid');
        console.error('  4. Ensure network connectivity');

        return false;
    }
}

// Run test
if (require.main === module) {
    testFirstCycle()
        .then(success => {
            process.exit(success ? 0 : 1);
        })
        .catch(error => {
            console.error('Unexpected error:', error);
            process.exit(1);
        });
}

module.exports = testFirstCycle;
