@echo off
title Ghost Agent - Aplicar BrowserAllowlist
color 0A

echo.
echo ========================================
echo  GHOST AGENT - BROWSER ALLOWLIST
echo  Aplicar Configuracion Automatica
echo ========================================
echo.

:: Ruta del allowlist
set "ALLOWLIST_PATH=%USERPROFILE%\.gemini\antigravity\browserAllowlist.txt"

echo [1/3] Verificando archivo browserAllowlist.txt...
echo.

if exist "%ALLOWLIST_PATH%" (
    echo    [OK] Archivo existe: %ALLOWLIST_PATH%
    echo.
    echo    Contenido actual:
    echo    ----------------------------------------
    type "%ALLOWLIST_PATH%"
    echo    ----------------------------------------
) else (
    echo    [!] Archivo NO existe - creando...
    
    if not exist "%USERPROFILE%\.gemini\antigravity" (
        mkdir "%USERPROFILE%\.gemini\antigravity" 2>NUL
    )
    
    (
    echo # MEGA BrowserAllowlist - Auto-generated by Ghost Agent
    echo # Allows ALL websites and domains
    echo.
    echo *
    echo *.*
    echo *://*
    echo http://*
    echo https://*
    echo localhost
    echo localhost:*
    echo *.localhost
    echo 127.0.0.1:*
    echo 192.168.*.*
    echo *.com
    echo *.net
    echo *.org
    echo *.io
    echo *.dev
    echo *.app
    echo *.ai
    echo *.cloud
    echo *.github.io
    echo *.vercel.app
    echo *.netlify.app
    ) > "%ALLOWLIST_PATH%"
    
    echo    [OK] Archivo creado
)

echo.
echo [2/3] Cerrando Antigravity para aplicar cambios...
echo.

tasklist /FI "IMAGENAME eq Antigravity.exe" 2>NUL | find /I /N "Antigravity.exe">NUL
if "%ERRORLEVEL%"=="0" (
    echo    [i] Cerrando Antigravity...
    taskkill /IM "Antigravity.exe" /F >NUL 2>&1
    timeout /t 2 >NUL
    echo    [OK] Antigravity cerrado
) else (
    echo    [i] Antigravity no estaba corriendo
)

echo.
echo [3/3] Iniciando Antigravity...
echo.

set "ANTIGRAVITY_EXE=%USERPROFILE%\AppData\Local\Programs\AntiGravity\AntiGravity.exe"

if exist "%ANTIGRAVITY_EXE%" (
    echo    [i] Iniciando: %ANTIGRAVITY_EXE%
    start "" "%ANTIGRAVITY_EXE%"
    timeout /t 2 >NUL
    echo    [OK] Antigravity iniciado
) else (
    echo    [X] ERROR: No se encontro Antigravity.exe
    echo    [i] Ruta esperada: %ANTIGRAVITY_EXE%
)

echo.
echo ========================================
echo  CONFIGURACION APLICADA
echo ========================================
pause
