// GENESIS BUILDER LOGIC
// Project: AntiGravity Extension Creator

const state = {
    timeline: [],
    draggedItem: null
};

document.addEventListener('DOMContentLoaded', () => {
    console.log("Genesis Engine Loaded.");
    if (typeof COMMAND_DB === 'undefined') {
        alert("CRITICAL ERROR: data.js not loaded.");
        return;
    }

    const searchInput = document.getElementById('search-box');
    const pool = document.getElementById('command-pool');
    const timeline = document.getElementById('timeline');
    const exportBtn = document.getElementById('btn-export');

    // Initial Render (Limit to 100 for perf)
    renderPool('');

    // Search Listener
    searchInput.addEventListener('input', (e) => {
        const query = e.target.value.toLowerCase();
        renderPool(query);
    });

    // Drag Over
    timeline.addEventListener('dragover', (e) => {
        e.preventDefault();
        timeline.classList.add('drag-over');
    });

    timeline.addEventListener('dragleave', () => {
        timeline.classList.remove('drag-over');
    });

    // Drop
    timeline.addEventListener('drop', (e) => {
        e.preventDefault();
        timeline.classList.remove('drag-over');

        if (state.draggedItem) {
            addToTimeline(state.draggedItem);
            state.draggedItem = null;
        }
    });

    // Export
    exportBtn.addEventListener('click', generateExtensionCode);

    function renderPool(query) {
        pool.innerHTML = '';
        const limit = 50;
        let count = 0;

        for (const cmd of COMMAND_DB) {
            if (count >= limit) break;

            // Filter
            const match = cmd.command.toLowerCase().includes(query) ||
                (cmd.key && cmd.key.toLowerCase().includes(query));

            if (match) {
                const el = document.createElement('div');
                el.className = 'command-item';
                el.draggable = true;
                el.innerHTML = `
                    <div class="cmd-id">${cmd.command}</div>
                    ${cmd.key ? `<span class="cmd-key">⌨ ${cmd.key}</span>` : ''}
                    ${cmd.when ? `<span class="cmd-when">❓ ${cmd.when}</span>` : ''}
                `;

                el.addEventListener('dragstart', () => {
                    state.draggedItem = cmd;
                    el.style.opacity = '0.5';
                });

                el.addEventListener('dragend', () => {
                    el.style.opacity = '1';
                });

                pool.appendChild(el);
                count++;
            }
        }
    }

    function addToTimeline(cmd) {
        state.timeline.push(cmd);
        renderTimeline();
    }

    function renderTimeline() {
        timeline.innerHTML = '';
        state.timeline.forEach((cmd, index) => {
            const block = document.createElement('div');
            block.className = 'timeline-block';
            block.innerHTML = `
                <div>
                    <strong>Step ${index + 1}:</strong> ${cmd.command}
                </div>
                <div class="block-actions">
                    <span class="btn-del" onclick="removeFromTimeline(${index})">✖</span>
                </div>
            `;
            timeline.appendChild(block);
        });
    }

    window.removeFromTimeline = (index) => {
        state.timeline.splice(index, 1);
        renderTimeline();
    };

    function generateExtensionCode() {
        if (state.timeline.length === 0) {
            alert("Timeline is empty!");
            return;
        }

        let code = `// GENERATED BY ANTIGRAVITY GENESIS\n`;
        code += `const vscode = require('vscode');\n\n`;
        code += `async function activate(context) {\n`;
        code += `    console.log('Genesis Extension Activated');\n\n`;
        code += `    // EXECUTION FLOW\n`;

        state.timeline.forEach((cmd, i) => {
            code += `    // Step ${i + 1}: ${cmd.command}\n`;
            code += `    await vscode.commands.executeCommand('${cmd.command}');\n`;
            code += `    await new Promise(r => setTimeout(r, 500)); // Default Delay\n\n`;
        });

        code += `}\n\nmodule.exports = { activate };`;

        // Save to file (Simulator)
        console.log(code);

        // Trigger download
        const blob = new Blob([code], { type: 'text/javascript' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'extension.js';
        a.click();
    }
});
