/**
 * GENERATED BY ANTIGRAVITY GENESIS (AGENT SESSION)
 * File: antigravity_focus_protocol.js
 * Date: 2025-12-17T12:50:00Z
 * Mode: Agent Creation via WebBuilder
 */
const vscode = require('vscode');

async function activate(context) {
    vscode.window.showInformationMessage('🚀 Genesis Running: antigravity_focus_protocol');

    let disposable = vscode.commands.registerCommand('antigravity_focus_protocol.run', async () => {
        // [Step 1] Close Sidebar (Delay: 500ms)
        await vscode.commands.executeCommand('workbench.action.closeSidebar');
        await new Promise(r => setTimeout(r, 500));

        // [Step 2] Close Auxiliary Bar (Delay: 500ms)
        await vscode.commands.executeCommand('workbench.action.closeAuxiliaryBar');
        await new Promise(r => setTimeout(r, 500));

        // [Step 3] Close Panel (Delay: 500ms)
        await vscode.commands.executeCommand('workbench.action.closePanel');
        await new Promise(r => setTimeout(r, 500));

        // [Step 4] Toggle Zen Mode (Delay: 1000ms)
        await vscode.commands.executeCommand('workbench.action.toggleZenMode');
        await new Promise(r => setTimeout(r, 1000));

        // [Step 5] Chat Open (Delay: 500ms)
        await vscode.commands.executeCommand('workbench.action.chat.open');
        await new Promise(r => setTimeout(r, 500));

    });

    context.subscriptions.push(disposable);
    // Auto-Run
    vscode.commands.executeCommand('antigravity_focus_protocol.run');
}

function deactivate() { }

module.exports = { activate, deactivate };
